spring:
  application:
    name: gateway-service
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: 192.168.88.147
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.88.1:8848 #服务注册中心地址
    gateway:
      routes:
        - id: management_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://film-management-service #匹配后提供服务的路由地址
          predicates:
            - Path=/admin/**,/film/**,/arrange/** #断言,路径相匹配的进行路由
        - id: management_routh2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://user-service #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**,/comment/**,/order/** #断言,路径相匹配的进行路由
        - id: sms_routh3 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://sms #匹配后提供服务的路由地址
          predicates:
            - Path=/sms/** #断言,路径相匹配的进行路由
        - id: oss_routh4 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://oss #匹配后提供服务的路由地址
          predicates:
            - Path=/upload/** #断言,路径相匹配的进行路由
      # gateway的全局跨域请求配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods: "*"
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_UNIQUE
server:
  port: 1111
